# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkoutCompanion' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SCLAlertView'
  # Pods for WorkoutCompanion

  target 'WorkoutCompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorkoutCompanionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
